
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "crystal"

[enderio]
	#The default byproduct material to output in Ender IO's sagmill.
	byproduct = "minecraft:cobblestone"

[hbm]
	#Should this ore use sulfuric acid in HBMNTM's crystallizer.
	byproduct = false

